version: '3.9'
services:
  app:
    container_name: app_container
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=saferman14
      - POSTGRES_DB=library-api
      - DB_HOST=postgresdb
      - DB_PORT=5432
      # - TEST_POSTGRES_USER=${TEST_DB_USER}
      # - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      # - TEST_POSTGRES_DB=${TEST_DB_NAME}
      # - TEST_DATABASE_HOST=${TEST_DB_HOST}
      # - TEST_DATABASE_PORT=${TEST_DB_PORT}
    tty: true
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - library-api

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=saferman14
      - POSTGRES_DB=gin_db
      - DATABASE_HOST=localhost
    ports:
      - '1234:5432'
    networks:
      - library-api
    # Mount init.sql file to automatically run 
    # and create tables for us.
    # everything in data folder
    # is executed as soon as container is up nd running.
    volumes:
      - "./db/db-dumb.sql:/docker-entrypoint-initdb.d/db_dumb.sql"

# Networks to be created to facilitate communication between containers
networks:
  library-api:
    driver: bridge