version: '3.18'
services:
  app:
    container_name: gorm-raw-app
    image: 'gorm-raw/backend'
    environment:
      - 'GIN_MODE=${GIN_MODE}'
      - 'DB_HOST=${DB_HOST_DOCKER}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASS=${DB_PASS}'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_PORT=${DB_PORT}'
      - 'APP_PORT=${APP_PORT}'
      - 'JWT_ISSUER=${JWT_ISSUER}'
      - 'JWT_EXPIRES_AT=${JWT_EXPIRES_AT}'
      - 'JWT_SECRET=${JWT_SECRET}'
    build: .
    ports: 
      - 3000:3000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - gorm-raw_postgres          # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
    expose:
      - ${APP_PORT}
    networks:
      - fullstack


  gorm-raw_postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gorm-raw_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - gorm-raw_postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

  
  # fullstack-mysql:
  #   image: mysql:5.7
  #   container_name: full_db_mysql
  #   ports: 
  #     - 3306:3306
  #   environment: 
  #     - MYSQL_ROOT_HOST=${DB_HOST} 
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - database_mysql:/var/lib/mysql
  #   networks:
  #     - fullstack
  
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin_container
  #   depends_on:
  #     - fullstack-mysql
  #   environment:
  #     - PMA_HOST=mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
  #     - PMA_USER=${DB_USER}
  #     - PMA_PORT=${DB_PORT}
  #     - PMA_PASSWORD=${DB_PASSWORD}
  #   ports:
  #     - 9090:80
  #   restart: always
  #   networks:
  #     - fullstack


volumes:
  api:
  database_postgres:                  # Uncomment this when using postgres.
  # database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge