[Application]
environment="development"
port=8080
baseUrl="http://localhost"
slugLength=6

[Database]
host="go-url-shortener-study-case-db-1"
name="dummy_data2"
port=5432
password="saferman14"
user="postgres"

[Redis]
host="go-url-shortener-study-case-cache-1"
port=6380

[Asynq]
concurrentWorker=10
queuesCritical=6
queuesDefault=3
queuesLow=1
