# Doing multi stage build, so the container is not too large
FROM golang:1.19-alpine AS builder

# Add Maintainer Info
LABEL maintainer="Digitalent"

WORKDIR /app

COPY go.mod /app
COPY go.sum /app
RUN go mod download

COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/worker/main.go

FROM alpine:3 as dev

WORKDIR /app

COPY --from=builder /app/main /app

EXPOSE 8080

ENTRYPOINT ["./main"]